---
title: "Module3"
author: "HanGyuKang"
date: "11/15/2020"
output: html_document
---
```{r}
require(nnet)
```

```{r}
dat <- read.csv("Data/df.csv",header=TRUE)
star.dat <- dat[,c(2,11:dim(dat)[2])]
```

```{r}
words <- apply(star.dat[,2:dim(star.dat)[2]],2,sum)

wordembedding.dat <- star.dat
for (i in 1:dim(star.dat)[2]-1){
  wordembedding.dat[which(star.dat[,i+1] >=1),i+1]=1
}
stars <- star.dat[,1]
wordembedding.dat <- wordembedding.dat[names(sort(words[words>summary(words)[5]], decreasing= TRUE))]
wordembedding.dat <- cbind(stars,wordembedding.dat)
wordembedding.dat$stars <- as.factor(wordembedding.dat$stars)
```
```{r}
freq <- function(argument1){
ind <- argument1
total.star1 <-length(which(wordembedding.dat$stars == 1))
total.star2 <-length(which(wordembedding.dat$stars == 2))
total.star3 <-length(which(wordembedding.dat$stars == 3))
total.star4 <-length(which(wordembedding.dat$stars == 4))
total.star5 <-length(which(wordembedding.dat$stars == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(wordembedding.dat$stars, wordembedding.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] == 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] == 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] == 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] == 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] == 1))
v <- c(star1, star2, star3, star4, star5)

freq <- v/total.v
freq
}

freq.mat <- matrix(rep(NA,5),nrow=5)
for (i in 1:dim(wordembedding.dat)[2]-1){
  freq.vec <- freq(colnames(wordembedding.dat)[i+1])
  freq.mat <- cbind(freq.mat,freq.vec)
}
stars <- levels(as.factor(star.dat$stars_x))
freq.data <- freq.mat[,-(1:2)]
colnames(freq.data) <- names(wordembedding.dat)[-1]
freq.data <- as.data.frame(cbind(stars,freq.data))
```
```{r}
avg.hotel <- sort(tapply(dat$stars_x,dat$name,mean))
avg.hotel
summary(avg.hotel)
```
```{r}
length(avg.hotel[which(avg.hotel< 3.5)])
par(cex.axis=1)
barplot(avg.hotel[avg.hotel < 3.5], main = "Average rate of the Hotels who received lower rate in Madison", ylim = c(0,5),las=2)
lowrate.Hotels <- names(avg.hotel[avg.hotel < 3.5])
lowrate.Hotels
```
```{r}
rev <- c()
for(i in 1:22){
    rev[i] <- length(dat$stars_x[which(dat$name==lowrate.Hotels[i])])
}
sum(rev)

ref <- c()
for (i in 1:23){
   temp <- which(dat$name==lowrate.Hotels[i])
   ref <- c(ref,temp) 
}

lowerhotel.dat <- dat[ref,-c(1,3:10)]
stars <- lowerhotel.dat[,1]
lowerhotel.dat <- cbind(stars, lowerhotel.dat[names(sort(words[words>summary(words)[5]], decreasing= TRUE))])
```
```{r}
length(avg.hotel[avg.hotel > 3.5])
par(cex.axis=1)
barplot(avg.hotel[avg.hotel > 3.5], main = "Average rate of the Hotels who received better rate in Madison", ylim = c(0,5),las=2)
highrate.Hotels <- names(avg.hotel[avg.hotel > 3.5])
highrate.Hotels
```
```{r}
rev <- c()
for(i in 1:23){
    rev[i] <- length(dat$stars_x[which(dat$name==highrate.Hotels[i])])
}
sum(rev)

ref <- c()
for (i in 1:23){
   temp <- which(dat$name==highrate.Hotels[i])
   ref <- c(ref,temp) 
}

betterhotel.dat <- dat[ref,-c(1,3:10)]
stars <- betterhotel.dat[,1]
betterhotel.dat <- cbind(stars, betterhotel.dat[names(sort(words[words>summary(words)[5]], decreasing= TRUE))])
```


```{r}
lower.freq <- function(argument1){
ind <- argument1
total.star1 <-length(which(lowerhotel.dat$stars == 1))
total.star2 <-length(which(lowerhotel.dat$stars == 2))
total.star3 <-length(which(lowerhotel.dat$stars == 3))
total.star4 <-length(which(lowerhotel.dat$stars == 4))
total.star5 <-length(which(lowerhotel.dat$stars == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(lowerhotel.dat$stars, lowerhotel.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] == 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] == 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] == 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] == 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] == 1))
v <- c(star1, star2, star3, star4, star5)

freq <- v/total.v
freq
}

better.freq <- function(argument1){
ind <- argument1
total.star1 <-length(which(betterhotel.dat$stars == 1))
total.star2 <-length(which(betterhotel.dat$stars == 2))
total.star3 <-length(which(betterhotel.dat$stars == 3))
total.star4 <-length(which(betterhotel.dat$stars == 4))
total.star5 <-length(which(betterhotel.dat$stars == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(betterhotel.dat$stars, betterhotel.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] == 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] == 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] == 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] == 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] == 1))
v <- c(star1, star2, star3, star4, star5)

freq <- v/total.v
freq
}



freq.lower.mat <- matrix(rep(NA,5),nrow=5)
for (i in 1:dim(lowerhotel.dat)[2]-2){
  freq.lower.vec <- lower.freq(colnames(lowerhotel.dat)[i+2])
  freq.lower.mat <- cbind(freq.lower.mat,freq.lower.vec)
}

freq.higher.mat <- matrix(rep(NA,5),nrow=5)
for (i in 1:dim(betterhotel.dat)[2]-2){
  freq.higher.vec <- better.freq(colnames(betterhotel.dat)[i+2])
  freq.higher.mat <- cbind(freq.higher.mat,freq.higher.vec)
}

stars <- levels(as.factor(wordembedding.dat$stars))

freq.lower.mat <- freq.lower.mat[,-(1:2)]
freq.higher.mat <- freq.higher.mat[,-(1:2)]

colnames(freq.lower.mat) <- names(wordembedding.dat)[-1]
colnames(freq.higher.mat) <- names(wordembedding.dat)[-1]

grade <- rep("lower",5)
lower.freq.dat <- as.data.frame(cbind(grade,stars,freq.lower.mat))

grade <- rep("better",5)
better.freq.dat <- as.data.frame(cbind(grade,stars,freq.higher.mat))

frequency.dat <- rbind(lower.freq.dat,better.freq.dat)
frequency.dat <- type.convert(frequency.dat)
frequency.dat$stars <- as.factor(frequency.dat$stars)
```



```{r}

```

```{r}
word.frequency <- function(argument1){
ind <- argument1
total.star1 <-length(which(wordembedding.dat$stars == 1))
total.star2 <-length(which(wordembedding.dat$stars == 2))
total.star3 <-length(which(wordembedding.dat$stars == 3))
total.star4 <-length(which(wordembedding.dat$stars == 4))
total.star5 <-length(which(wordembedding.dat$stars == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(wordembedding.dat$star,wordembedding.dat[,ind])
star1 <-length(which(wordembedding.dat[,1] == 1 & freq.dat[,2] >= 1))
star2 <-length(which(wordembedding.dat[,1] == 2 & freq.dat[,2] >= 1))
star3 <-length(which(wordembedding.dat[,1] == 3 & freq.dat[,2] >= 1))
star4 <-length(which(wordembedding.dat[,1] == 4 & freq.dat[,2] >= 1))
star5 <-length(which(wordembedding.dat[,1] == 5 & freq.dat[,2] >= 1))
v <- c(star1, star2, star3, star4, star5)

Frequency <- v/total.v

barplot(Frequency, xlab = "Rates", ylab = "Word Frequency", main=ind)
}
```

```{r}
par(mfrow=c(3,3))
word.frequency("great")
word.frequency("nice")
word.frequency("good")
word.frequency("bad")
word.frequency("like")
word.frequency("well")
word.frequency("best")
word.frequency("better")
word.frequency("love")
word.frequency("recommend")
word.frequency("awesome")
word.frequency("perfect")
word.frequency("wonderful")
word.frequency("enjoyed")
word.frequency("excellent")
```


```{r}
par(mfrow=c(3,3))
word.frequency("staff")
word.frequency("service")
word.frequency("employee")
word.frequency("manager")
word.frequency("reservation")
word.frequency("breakfast")
word.frequency("coffee")
word.frequency("drink")
word.frequency("price")
word.frequency("suite")
word.frequency("bed")
word.frequency("desk")
word.frequency("wifi")
word.frequency("tv")
word.frequency("fridge")
word.frequency("pillow")
word.frequency("towel")
```

```{r}
par(mfrow=c(3,3))
word.frequency("room")
word.frequency("bathroom")
word.frequency("pool")
word.frequency("tub")
word.frequency("shower")
word.frequency("lobby")
word.frequency("elevator")
word.frequency("wall")
word.frequency("parking")
word.frequency("gym")
word.frequency("amenity")
```
```{r}
par(mfrow=c(3,3))
word.frequency("shuttle")
word.frequency("downtown")
word.frequency("airport")
word.frequency("distance")
word.frequency("bar")
word.frequency("location")
word.frequency("restaurant")
word.frequency("park")
word.frequency("near")
```
```{r}
par(mfrow=c(3,3))
word.frequency("family")
word.frequency("kid")
word.frequency("clean")
word.frequency("comfortable")
word.frequency("small")
word.frequency("pretty")
word.frequency("quiet")
word.frequency("beautiful")
word.frequency("spacious")
word.frequency("modern")
word.frequency("noise")
word.frequency("smell")
word.frequency("comfy")
```

```{r}
freq <- function(argument1){
ind <- argument1
total.star1 <-length(which(star.dat$stars_x == 1))
total.star2 <-length(which(star.dat$stars_x == 2))
total.star3 <-length(which(star.dat$stars_x == 3))
total.star4 <-length(which(star.dat$stars_x == 4))
total.star5 <-length(which(star.dat$stars_x == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(star.dat$stars_x,star.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] >= 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] >= 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] >= 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] >= 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] >= 1))
v <- c(star1, star2, star3, star4, star5)

freq <- v/total.v
freq
}

freq.mat <- matrix(rep(NA,5),nrow=5)
for (i in 1:dim(star.dat)[2]-1){
  freq.vec <- freq(colnames(star.dat)[i+1])
  freq.mat <- cbind(freq.mat,freq.vec)
}
star.level <- levels(as.factor(star.dat$stars_x))
freq.data <- freq.mat[,-(1:2)]
colnames(freq.data) <- colnames(star.dat)[2:dim(star.dat)[2]]
freq.data <- as.data.frame(cbind(star.level,freq.data))

wordembedding.dat <- star.dat
for (i in 1:dim(star.dat)[2]-1){
  wordembedding.dat[which(star.dat[,i+1] >=1),i+1]=1
}
stars <- star.dat[,1]
wordembedding.dat <- cbind(stars,wordembedding.dat[,-1])
wordembedding.dat$stars <- as.factor(wordembedding.dat$stars)
```


```{r}
test.dat <- wordembedding.dat[c("stars","staff", "manager", "breakfast", "desk","parking","wall","location","bar","clean","comfortable","spacious","smell")]

staff <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,2]==1){
    if (test.dat[i,]$stars==1){
    staff[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    staff[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    staff[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    staff[i] = 4
    }
    else {
    staff[i] = 5
    }
  }
  else{
    staff[i] = 3
  }
}

manager <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,3]==1){
    if (test.dat[i,]$stars==1){
    manager[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    manager[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    manager[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    manager[i] = 4
    }
    else {
    manager[i] = 5
    }
  }
  else{
    manager[i] = 3
  }
}

breakfast <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,4]==1){
    if (test.dat[i,]$stars==1){
    breakfast[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    breakfast[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    breakfast[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    breakfast[i] = 4
    }
    else {
    breakfast[i] = 5
    }
  }
  else{
    breakfast[i] = 3
  }
}

desk <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,5]==1){
    if (test.dat[i,]$stars==1){
    desk[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    desk[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    desk[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    desk[i] = 4
    }
    else {
    desk[i] = 5
    }
  }
  else{
    desk[i] = 3
  }
}

parking <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,6]==1){
    if (test.dat[i,]$stars==1){
    parking[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    parking[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    parking[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    parking[i] = 4
    }
    else {
    parking[i] = 5
    }
  }
  else{
    parking[i] = 3
  }
}

wall <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,7]==1){
    if (test.dat[i,]$stars==1){
    wall[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    wall[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    wall[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    wall[i] = 4
    }
    else {
    wall[i] = 5
    }
  }
  else{
    wall[i] = 3
  }
}

location <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,8]==1){
    if (test.dat[i,]$stars==1){
    location[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    location[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    location[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    location[i] = 4
    }
    else {
    location[i] = 5
    }
  }
  else{
    location[i] = 3
  }
}

bar <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,9]==1){
    if (test.dat[i,]$stars==1){
    bar[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    bar[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    bar[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    bar[i] = 4
    }
    else {
    bar[i] = 5
    }
  }
  else{
    bar[i] = 3
  }
}

clean <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,10]==1){
    if (test.dat[i,]$stars==1){
    clean[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    clean[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    clean[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    clean[i] = 4
    }
    else {
    clean[i] = 5
    }
  }
  else{
    clean[i] = 3
  }
}

comfortable <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,11]==1){
    if (test.dat[i,]$stars==1){
    comfortable[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    comfortable[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    comfortable[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    comfortable[i] = 4
    }
    else {
    comfortable[i] = 5
    }
  }
  else{
    comfortable[i] = 3
  }
}

spacious <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,12]==1){
    if (test.dat[i,]$stars==1){
    spacious[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    spacious[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    spacious[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    spacious[i] = 4
    }
    else {
    spacious[i] = 5
    }
  }
  else{
    spacious[i] = 3
  }
}

smell <- c()
for(i in 1:dim(test.dat)[1]){
  if (test.dat[i,13]==1){
    if (test.dat[i,]$stars==1){
    smell[i] = 1
    }
    else if(test.dat[i,]$stars==2){
    smell[i] = 2
    }
    else if(test.dat[i,]$stars==3){
    smell[i] = 3
    }
    else if(test.dat[i,]$stars==4){
    smell[i] = 4
    }
    else {
    smell[i] = 5
    }
  }
  else{
    smell[i] = 3
  }
}

stars <- as.factor(test.dat$stars)
eval.dat <- as.data.frame(cbind(stars,staff,manager,breakfast,desk,parking,wall,location,bar,clean,comfortable,spacious,smell))

eval.m <- multinom(stars~.,data=eval.dat)
summary(eval.m)
table(predict(eval.m,eval.dat),stars)


sum(diag(table(predict(eval.m,eval.dat),stars)))/sum(table(predict(eval.m,eval.dat),stars))
```

```{r}
barplot(table(eval.dat$stars))
barplot(table(eval.dat$staff))
barplot(table(eval.dat$manager))
barplot(table(eval.dat$breakfast))
barplot(table(eval.dat$desk))
barplot(table(eval.dat$parking))
barplot(table(eval.dat$wall))
barplot(table(eval.dat$location))
barplot(table(eval.dat$bar))
barplot(table(eval.dat$clean))
barplot(table(eval.dat$comfortable))
barplot(table(eval.dat$spacious))
barplot(table(eval.dat$smell))

```

```{r}
anova(lm(room+bath+pool+tub+shower+lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(bath+pool+tub+shower+lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(pool+tub+shower+lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(tub+shower+lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(shower+lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(lobby+elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(elevator+wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(wall+parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(parking+facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(facility+gym+amenity~stars, data = wordembedding.dat))
anova(lm(gym+amenity~stars, data = wordembedding.dat))
anova(lm(amenity~stars, data = wordembedding.dat))

anova(lm(shuttle+downtown+airport+bus+distance+bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(downtown+airport+bus+distance+bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(airport+bus+distance+bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(bus+distance+bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(distance+bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(bar+location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(location+restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(restaurant+park+security+near~stars, data = wordembedding.dat))
anova(lm(park+security+near~stars, data = wordembedding.dat))
anova(lm(security+near~stars, data = wordembedding.dat))
anova(lm(near~stars, data = wordembedding.dat))

anova(lm(family+kid+clean+comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(kid+clean+comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(clean+comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(small+pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(pretty+quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(quiet+beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(beautiful+spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(spacious+modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(modern+noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(noise+smell+comfy~stars, data = wordembedding.dat))
anova(lm(smell+comfy~stars, data = wordembedding.dat))
anova(lm(comfy~stars, data = wordembedding.dat))
```
```{r}
anova(lm(room~stars, data = dup.dat))
anova(lm(bed~stars, data = dup.dat))
anova(lm(desk~stars, data = dup.dat))
anova(lm(bathroom~stars, data = dup.dat))
anova(lm(pool~stars, data = dup.dat))
anova(lm(tub~stars, data = dup.dat))
anova(lm(shower~stars, data = dup.dat))
anova(lm(lobby~stars, data = dup.dat))
anova(lm(wifi~stars, data = dup.dat))
anova(lm(tv~stars, data = dup.dat))
anova(lm(fridge~stars, data = dup.dat))
anova(lm(window~stars, data = dup.dat))
anova(lm(wall~stars, data = dup.dat))
anova(lm(pillow~stars, data = dup.dat))
anova(lm(parking~stars, data = dup.dat))
anova(lm(suite~stars, data = dup.dat))
anova(lm(facility~stars, data = dup.dat))
anova(lm(towel~stars, data = dup.dat))
anova(lm(gym~stars, data = dup.dat))
```
```{r}
anova(lm(shuttle~stars, data = dup.dat))
anova(lm(downtown~stars, data = dup.dat))
anova(lm(airport~stars, data = dup.dat))
anova(lm(bus~stars, data = dup.dat))
anova(lm(drink~stars, data = dup.dat))
anova(lm(distance~stars, data = dup.dat))
anova(lm(bar~stars, data = dup.dat))
anova(lm(location~stars, data = dup.dat))
anova(lm(restaurant~stars, data = dup.dat))
anova(lm(park~stars, data = dup.dat))
anova(lm(security~stars, data = dup.dat))
```
```{r}
anova(lm(family~stars, data = dup.dat))
anova(lm(kid~stars, data = dup.dat))
anova(lm(clean~stars, data = dup.dat))
anova(lm(comfortable~stars, data = dup.dat))
anova(lm(small~stars, data = dup.dat))
anova(lm(pretty~stars, data = dup.dat))
anova(lm(quiet~stars, data = dup.dat))
anova(lm(beautiful~stars, data = dup.dat))
anova(lm(spacious~stars, data = dup.dat))
anova(lm(modern~stars, data = dup.dat))
anova(lm(noise~stars, data = dup.dat))
anova(lm(smell~stars, data = dup.dat))
```

```{r}

m1 <- multinom(stars~staff+service+wait+rude+manager+helpful+decent+employee+friendly+management+reservation+breakfast+coffee+room+bed+desk+bathroom+pool+tub+shower+lobby+wifi+tv+elevator+fridge+window+wall+pillow+parking+suite+facility+towel+gym+shuttle+downtown+airport+bus+drink+distance+bar+location+restaurant+park+security+family+kid+clean+comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell, data = wordembedding.dat)

summary(m1)

m2 <- multinom(stars~staff+employee+friendly+management+reservation+breakfast+coffee+room+bed+desk+bathroom+pool+tub+shower+lobby+wifi+tv+elevator+fridge+window+wall+pillow+parking+suite+facility+towel+gym+shuttle+downtown+airport+bus+drink+distance+bar+location+restaurant+park+security+family+kid+clean+comfortable+small+pretty+quiet+beautiful+spacious+modern+noise+smell, data = dup.dat)

predict(m1, dup.dat)


predict(m2, dup.dat)

summary(m1)

library(nnet)
m3 <- multinom(stars~room+second+floor+nice+decor+furniture,data = dup.dat)
predict(m1,newdata = dup.dat)
summary(m1)
```

```{r}
avg.hotel <- sort(tapply(dat$stars_x,dat$name,mean))
avg.hotel[avg.hotel > avg.hotel["AC Hotel by Marriott Madison Downtown"]]
barplot(avg.hotel[avg.hotel > avg.hotel["AC Hotel by Marriott Madison Downtown"]], main = "Average Rate of Hotel Greater than AC Hotel in Madison", ylim = c(0,5),las=2)
```
```{r}
review.len <- c()
for(i in 1:length(names(avg.hotel))){
review.len[i] <- length(dat$stars_x[which(dat$name==names(avg.hotel)[i])])
}

length(dat$stars_x[which(dat$name=="AC Hotel by Marriott Madison Downtown")])
barplot(table(dat$stars_x[which(dat$name==names(avg.hotel)[22])]),xlab="Stars",ylab="Number of Review", main=names(avg.hotel)[22], cex.main = 0.7)

ac.dat <- dat[which(dat$name=="AC Hotel by Marriott Madison Downtown"),-c(1,3:10)]
ac.words <- apply(ac.dat[,2:dim(ac.dat)[2]],2,sum)
sort(ac.words[ac.words>summary(ac.words)[5]], decreasing= TRUE)
```

```{r}
word.ac.frequency <- function(argument1){
ind <- argument1
total.star1 <-length(which(ac.dat$stars_x == 1))
total.star2 <-length(which(ac.dat$stars_x == 2))
total.star3 <-length(which(ac.dat$stars_x == 3))
total.star4 <-length(which(ac.dat$stars_x == 4))
total.star5 <-length(which(ac.dat$stars_x == 5))
total.v <- c(total.star1,total.star2,total.star3,total.star4,total.star5)

freq.dat <- cbind(ac.dat$stars_x,ac.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] >= 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] >= 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] >= 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] >= 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] >= 1))
v <- c(star1, star2, star3, star4, star5)

Frequency <- v/total.v

barplot(Frequency, xlab = "Rates", ylab = "Word Frequency", main=ind)
}
```

```{r}
par(mfrow=c(3,3))
word.ac.frequency("nice")
word.ac.frequency("great")
word.ac.frequency("good")
word.ac.frequency("amazing")


word.ac.frequency("friendly")
word.ac.frequency("staff")
word.ac.frequency("service")


word.ac.frequency("room")
word.ac.frequency("bar")
word.ac.frequency("restaurant")

word.ac.frequency("location")

word.ac.frequency("view")
word.ac.frequency("modern")
word.ac.frequency("beautiful")
```
```{r}
freq.mat <- matrix(rep(NA,5),nrow=5)
for (i in 1:dim(star.dat)[2]-1){
  freq.vec <- freq(colnames(star.dat)[i+1])
  freq.mat <- cbind(freq.mat,freq.vec)
}
star.level <- levels(as.factor(star.dat$stars_x))
freq.data <- freq.mat[,-(1:2)]
colnames(freq.data) <- colnames(star.dat)[2:dim(star.dat)[2]]
freq.data <- as.data.frame(cbind(star.level,freq.data))

dup.dat <- star.dat
for (i in 1:dim(star.dat)[2]-1){
  dup.dat[which(star.dat[,i+1] >=1),i+1]=1
}
stars <- star.dat[,1]
dup.dat <- cbind(stars,dup.dat[,-1])
dup.dat$stars <- as.factor(dup.dat$stars)
```

















```{r}
dat2 <- read.csv("Data/df_tip.csv",header=TRUE)
tip.dat <- dat2[,c(2,11:dim(dat2)[2])]
tip.words <- apply(tip.dat[,2:dim(tip.dat)[2]],2,sum)
sort(tip.words, decreasing= TRUE)

word.tip.frequency <- function(argument1){
ind <- argument1
total.star1 <-length(which(tip.dat$stars == 1))
total.star1.5 <-length(which(tip.dat$stars == 1.5))
total.star2 <-length(which(tip.dat$stars == 2))
total.star2.5 <-length(which(tip.dat$stars == 2.5))
total.star3 <-length(which(tip.dat$stars == 3))
total.star3.5 <-length(which(tip.dat$stars == 3.5))
total.star4 <-length(which(tip.dat$stars == 4))
total.star4.5 <-length(which(tip.dat$stars == 4.5))
total.star5 <-length(which(tip.dat$stars == 5))
total.v <- c(total.star1,total.star1.5, total.star2, total.star2.5, total.star3, total.star3.5, total.star4,total.star4.5, total.star5)

freq.dat <- cbind(tip.dat$stars,tip.dat[,ind])
star1 <-length(which(freq.dat[,1] == 1 & freq.dat[,2] >= 1))
star1.5 <-length(which(freq.dat[,1] == 1.5 & freq.dat[,2] >= 1))
star2 <-length(which(freq.dat[,1] == 2 & freq.dat[,2] >= 1))
star2.5 <-length(which(freq.dat[,1] == 2.5 & freq.dat[,2] >= 1))
star3 <-length(which(freq.dat[,1] == 3 & freq.dat[,2] >= 1))
star3.5 <-length(which(freq.dat[,1] == 3.5 & freq.dat[,2] >= 1))
star4 <-length(which(freq.dat[,1] == 4 & freq.dat[,2] >= 1))
star4.5 <-length(which(freq.dat[,1] == 4.5 & freq.dat[,2] >= 1))
star5 <-length(which(freq.dat[,1] == 5 & freq.dat[,2] >= 1))
v <- c(star1, star1.5, star2, star2.5, star3, star3.5, star4, star4.5, star5)

Frequency <- v/total.v

barplot(Frequency, xlab = "Rates", ylab = "Word Frequency", main=ind)
}

word.tip.frequency("room")
```